[package]
name = "combiner"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
walkdir = "2.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"
tiktoken-rs = "0.5"
prettytable-rs = "0.10"
rayon = "1.10"
